print(2+3)
print(6/2)
print(2!=3)
print(5 or 6)
print([1,2,3].append("John"))
#the result here is none because list are mutable!
print("bubu"*2)
#print("bubu"*(4/2))
print(len(("abc",2)))
print(2+3*2**2)
